#!/usr/bin/env bash
# =============================================================================
# 16-configure-splunk.sh - Configure Splunk Enterprise on 10.10.0.66
# =============================================================================
# Configures Splunk for the ES-First IceDataEmphasise architecture:
# - Creates SIEM indexes (cribl_siem, cribl_siem_windows, cribl_siem_linux)
# - Activates HEC with existing token
# - Deploys props.conf, transforms.conf for Cribl sourcetypes
# - Deploys eventtypes.conf, tags.conf for CIM data models
# - Creates backups before every change
#
# Prerequisites:
#   - SSH key-based access to 10.10.0.66 (as root or splunk user)
#   - Splunk Enterprise installed at /opt/splunk
#
# Usage:
#   ./scripts/16-configure-splunk.sh
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

# =============================================================================
# Load environment
# =============================================================================
load_env "$PROJECT_DIR/.env"

# =============================================================================
# Configuration
# =============================================================================
SPLUNK_SSH_HOST="${SPLUNK_HOST:-10.10.0.66}"
SPLUNK_SSH_USER="${SPLUNK_SSH_USER:-root}"
SPLUNK_HOME="${SPLUNK_INSTALL_DIR:-/opt/splunk}"
SPLUNK_LOCAL_DIR="${SPLUNK_HOME}/etc/system/local"
SPLUNK_USER="${SPLUNK_ADMIN_USER:-admin}"
SPLUNK_PASS="${SPLUNK_ADMIN_PASSWORD:-}"
BACKUP_TIMESTAMP="$(date '+%Y%m%d_%H%M%S')"
BACKUP_DIR_REMOTE="/opt/splunk-backups/${BACKUP_TIMESTAMP}"

# =============================================================================
# Helper: Run command on Splunk server via SSH
# =============================================================================
splunk_ssh() {
    ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=accept-new \
        "${SPLUNK_SSH_USER}@${SPLUNK_SSH_HOST}" "$@"
}

splunk_scp() {
    scp -o ConnectTimeout=10 -o StrictHostKeyChecking=accept-new "$@"
}

# =============================================================================
# Main
# =============================================================================
main() {
    print_header "Configure Splunk Enterprise (${SPLUNK_SSH_HOST}) for ES-First Architecture"
    require_commands ssh scp

    if [[ -z "$SPLUNK_PASS" ]]; then
        die "SPLUNK_ADMIN_PASSWORD not set in .env"
    fi

    # =========================================================================
    # Step 1: Test SSH connection
    # =========================================================================
    log_step "Step 1/8: Test SSH connection to ${SPLUNK_SSH_HOST}"
    if splunk_ssh "echo 'SSH OK' && test -d ${SPLUNK_HOME}" 2>/dev/null; then
        log_ok "SSH connection OK, Splunk found at ${SPLUNK_HOME}"
    else
        die "Cannot connect via SSH to ${SPLUNK_SSH_USER}@${SPLUNK_SSH_HOST} or Splunk not at ${SPLUNK_HOME}"
    fi

    # =========================================================================
    # Step 2: Create backup of existing configs
    # =========================================================================
    log_step "Step 2/8: Backup existing Splunk configs"

    splunk_ssh "mkdir -p ${BACKUP_DIR_REMOTE} && \
        cp -a ${SPLUNK_LOCAL_DIR}/inputs.conf ${BACKUP_DIR_REMOTE}/ 2>/dev/null || true && \
        cp -a ${SPLUNK_LOCAL_DIR}/props.conf ${BACKUP_DIR_REMOTE}/ 2>/dev/null || true && \
        cp -a ${SPLUNK_LOCAL_DIR}/transforms.conf ${BACKUP_DIR_REMOTE}/ 2>/dev/null || true && \
        cp -a ${SPLUNK_LOCAL_DIR}/eventtypes.conf ${BACKUP_DIR_REMOTE}/ 2>/dev/null || true && \
        cp -a ${SPLUNK_LOCAL_DIR}/tags.conf ${BACKUP_DIR_REMOTE}/ 2>/dev/null || true && \
        cp -a ${SPLUNK_LOCAL_DIR}/indexes.conf ${BACKUP_DIR_REMOTE}/ 2>/dev/null || true && \
        ls -la ${BACKUP_DIR_REMOTE}/"

    log_ok "Backup saved to ${SPLUNK_SSH_HOST}:${BACKUP_DIR_REMOTE}"

    # =========================================================================
    # Step 3: Create SIEM indexes
    # =========================================================================
    log_step "Step 3/8: Create SIEM indexes"

    local indexes_conf
    indexes_conf=$(cat <<'INDEXES_EOF'
# =============================================================================
# indexes.conf - IceDataEmphasise SIEM Indexes
# Generated by 16-configure-splunk.sh
# =============================================================================

[cribl_siem]
homePath   = $SPLUNK_DB/cribl_siem/db
coldPath   = $SPLUNK_DB/cribl_siem/colddb
thawedPath = $SPLUNK_DB/cribl_siem/thaweddb
frozenTimePeriodInSecs = 7776000
maxTotalDataSizeMB = 51200

[cribl_siem_windows]
homePath   = $SPLUNK_DB/cribl_siem_windows/db
coldPath   = $SPLUNK_DB/cribl_siem_windows/colddb
thawedPath = $SPLUNK_DB/cribl_siem_windows/thaweddb
frozenTimePeriodInSecs = 7776000
maxTotalDataSizeMB = 20480

[cribl_siem_linux]
homePath   = $SPLUNK_DB/cribl_siem_linux/db
coldPath   = $SPLUNK_DB/cribl_siem_linux/colddb
thawedPath = $SPLUNK_DB/cribl_siem_linux/thaweddb
frozenTimePeriodInSecs = 7776000
maxTotalDataSizeMB = 20480
INDEXES_EOF
)

    # Merge with existing indexes.conf (append if missing)
    splunk_ssh "
        if [[ -f ${SPLUNK_LOCAL_DIR}/indexes.conf ]]; then
            if grep -q 'cribl_siem' ${SPLUNK_LOCAL_DIR}/indexes.conf 2>/dev/null; then
                echo 'indexes.conf: cribl_siem already configured'
            else
                echo '' >> ${SPLUNK_LOCAL_DIR}/indexes.conf
                cat >> ${SPLUNK_LOCAL_DIR}/indexes.conf <<'EOF'

${indexes_conf}
EOF
                echo 'indexes.conf: cribl_siem indexes appended'
            fi
        else
            cat > ${SPLUNK_LOCAL_DIR}/indexes.conf <<'EOF'
${indexes_conf}
EOF
            echo 'indexes.conf: created with cribl_siem indexes'
        fi
    "
    log_ok "SIEM indexes configured"

    # =========================================================================
    # Step 4: Configure HEC (HTTP Event Collector)
    # =========================================================================
    log_step "Step 4/8: Configure HEC"

    local hec_token="${SPLUNK_HEC_TOKEN:-}"
    if [[ -z "$hec_token" ]]; then
        log_warn "SPLUNK_HEC_TOKEN not set in .env, skipping HEC token configuration"
    fi

    local inputs_conf
    inputs_conf=$(cat <<INPUTS_EOF
# =============================================================================
# inputs.conf - IceDataEmphasise HEC Configuration
# Generated by 16-configure-splunk.sh
# =============================================================================

[http]
disabled = 0
port = ${SPLUNK_HEC_PORT:-8088}
enableSSL = 0
maxSockets = 0
maxThreads = 0
useDeploymentServer = 0

[http://cribl-stream-hec]
disabled = 0
token = ${hec_token}
index = cribl_siem
indexes = cribl_siem,cribl_siem_windows,cribl_siem_linux
sourcetype = cribl:siem
INPUTS_EOF
)

    echo "$inputs_conf" | splunk_ssh "cat > ${SPLUNK_LOCAL_DIR}/inputs.conf"
    log_ok "HEC configured on port ${SPLUNK_HEC_PORT:-8088} with token"

    # =========================================================================
    # Step 5: Deploy props.conf
    # =========================================================================
    log_step "Step 5/8: Deploy props.conf (Cribl sourcetypes)"

    local props_conf
    props_conf=$(cat <<'PROPS_EOF'
# =============================================================================
# props.conf - IceDataEmphasise Cribl SIEM Sourcetypes
# Generated by 16-configure-splunk.sh
# =============================================================================

# Cribl SIEM Events (allgemein)
[cribl:siem]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%Z
TIME_PREFIX = "(?:@timestamp|SYSLOG_TIMESTAMP)"\s*:\s*"
MAX_TIMESTAMP_LOOKAHEAD = 40
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
KV_MODE = json
TRUNCATE = 100000
TRANSFORMS-classification = cribl_classification_extract
TRANSFORMS-container = cribl_container_extract

# Windows Security Events (via Cribl Edge)
[cribl:siem:winsecurity]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%Z
SHOULD_LINEMERGE = false
KV_MODE = json
TRANSFORMS-eventid = cribl_win_eventid_extract

# Sysmon Events
[cribl:siem:sysmon]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%Z
SHOULD_LINEMERGE = false
KV_MODE = json

# Linux auditd Events
[cribl:siem:auditd]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%Z
SHOULD_LINEMERGE = false
KV_MODE = json

# Linux auth.log
[cribl:siem:linux_auth]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%Z
SHOULD_LINEMERGE = false
KV_MODE = json

# Sophos XG Firewall
[cribl:siem:sophos_fw]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%Z
SHOULD_LINEMERGE = false
KV_MODE = json
TRANSFORMS-sophos = cribl_sophos_extract

# Generic SIEM (fallback for SIEM-Discovery activated sources)
[cribl:siem:discovery]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%Z
SHOULD_LINEMERGE = false
KV_MODE = json
PROPS_EOF
)

    echo "$props_conf" | splunk_ssh "cat > ${SPLUNK_LOCAL_DIR}/props.conf"
    log_ok "props.conf deployed (7 sourcetypes)"

    # =========================================================================
    # Step 6: Deploy transforms.conf
    # =========================================================================
    log_step "Step 6/8: Deploy transforms.conf"

    local transforms_conf
    transforms_conf=$(cat <<'TRANSFORMS_EOF'
# =============================================================================
# transforms.conf - IceDataEmphasise Field Extractions
# Generated by 16-configure-splunk.sh
# =============================================================================

[cribl_classification_extract]
REGEX = "classification"\s*:\s*"([^"]+)"
FORMAT = classification::$1
WRITE_META = true

[cribl_container_extract]
REGEX = "CONTAINER_NAME"\s*:\s*"([^"]+)"
FORMAT = container_name::$1
WRITE_META = true

[cribl_win_eventid_extract]
REGEX = EventID["\s:=]+(\d+)
FORMAT = EventCode::$1
WRITE_META = true

[cribl_sophos_extract]
REGEX = "log_type"\s*:\s*"([^"]+)"
FORMAT = sophos_log_type::$1
WRITE_META = true
TRANSFORMS_EOF
)

    echo "$transforms_conf" | splunk_ssh "cat > ${SPLUNK_LOCAL_DIR}/transforms.conf"
    log_ok "transforms.conf deployed (4 transforms)"

    # =========================================================================
    # Step 7: Deploy eventtypes.conf & tags.conf (CIM)
    # =========================================================================
    log_step "Step 7/8: Deploy eventtypes.conf & tags.conf (CIM Data Models)"

    local eventtypes_conf
    eventtypes_conf=$(cat <<'EVENTTYPES_EOF'
# =============================================================================
# eventtypes.conf - IceDataEmphasise CIM Eventtypes
# Generated by 16-configure-splunk.sh
# =============================================================================

# Authentication events
[cribl_authentication]
search = index=cribl_siem* (classification_reason="security_keyword_match" OR classification_reason="access_control_keyword_match" OR classification_reason="windows_security_event_id") ("failed password" OR "authentication failure" OR "invalid user" OR EventID=4624 OR EventID=4625 OR EventID=4648)

# Endpoint events (Sysmon + auditd)
[cribl_endpoint_process]
search = index=cribl_siem* (classification_reason="sysmon_detection" OR classification_reason="auditd_security_event") (EventID=1 OR "type=EXECVE")

# Network events
[cribl_network_traffic]
search = index=cribl_siem* (EventID=3 OR "type=SOCKADDR" OR "type=CONNECT" OR classification_reason="access_control_keyword_match" AND ("blocked" OR "denied" OR "firewall"))

# Change events
[cribl_change_events]
search = index=cribl_siem* (EventID=4720 OR EventID=4732 OR EventID=7045 OR "type=USER_ACCT" OR "type=ADD_USER" OR "type=DEL_USER" OR classification_reason="auditd_security_event" AND ("useradd" OR "usermod" OR "groupadd"))

# Sophos Firewall events
[cribl_sophos_firewall]
search = index=cribl_siem* sourcetype="cribl:siem:sophos_fw"
EVENTTYPES_EOF
)

    echo "$eventtypes_conf" | splunk_ssh "cat > ${SPLUNK_LOCAL_DIR}/eventtypes.conf"
    log_ok "eventtypes.conf deployed (5 eventtypes)"

    local tags_conf
    tags_conf=$(cat <<'TAGS_EOF'
# =============================================================================
# tags.conf - IceDataEmphasise CIM Tags
# Generated by 16-configure-splunk.sh
# =============================================================================

[eventtype=cribl_authentication]
authentication = enabled
default = enabled

[eventtype=cribl_endpoint_process]
endpoint = enabled
process = enabled

[eventtype=cribl_network_traffic]
network = enabled
communicate = enabled

[eventtype=cribl_change_events]
change = enabled
audit = enabled

[eventtype=cribl_sophos_firewall]
network = enabled
communicate = enabled
TAGS_EOF
)

    echo "$tags_conf" | splunk_ssh "cat > ${SPLUNK_LOCAL_DIR}/tags.conf"
    log_ok "tags.conf deployed (5 tag groups)"

    # =========================================================================
    # Step 8: Restart Splunk & Verify
    # =========================================================================
    log_step "Step 8/8: Restart Splunk & Verify"

    log_info "Restarting Splunk on ${SPLUNK_SSH_HOST}..."
    splunk_ssh "${SPLUNK_HOME}/bin/splunk restart --accept-license --answer-yes --no-prompt" 2>&1 | tail -3
    log_ok "Splunk restarted"

    # Wait for Splunk to come up
    log_info "Waiting for Splunk to be ready..."
    sleep 10

    local verify_passed=0
    local verify_total=0

    # Check HEC health
    verify_total=$((verify_total + 1))
    local hec_health
    hec_health=$(curl -s -o /dev/null -w '%{http_code}' "http://${SPLUNK_SSH_HOST}:${SPLUNK_HEC_PORT:-8088}/services/collector/health" 2>/dev/null || echo "000")
    if [[ "$hec_health" == "200" ]]; then
        log_ok "VERIFY: HEC health check OK (HTTP 200)"
        verify_passed=$((verify_passed + 1))
    else
        log_error "VERIFY: HEC health check failed (HTTP ${hec_health})"
    fi

    # Test HEC event submission
    verify_total=$((verify_total + 1))
    local hec_test
    hec_test=$(curl -s "http://${SPLUNK_SSH_HOST}:${SPLUNK_HEC_PORT:-8088}/services/collector/event" \
        -H "Authorization: Splunk ${hec_token}" \
        -H "Content-Type: application/json" \
        -d '{"event":"IceDataEmphasise 16-configure-splunk.sh verification test","host":"cribl-stream","index":"cribl_siem","sourcetype":"cribl:siem"}' 2>/dev/null || echo '{}')
    if echo "$hec_test" | grep -q '"code":0'; then
        log_ok "VERIFY: HEC test event submitted successfully"
        verify_passed=$((verify_passed + 1))
    else
        log_error "VERIFY: HEC test event failed: ${hec_test}"
    fi

    # Check Splunk Web
    verify_total=$((verify_total + 1))
    local web_check
    web_check=$(curl -s -o /dev/null -w '%{http_code}' "http://${SPLUNK_SSH_HOST}:8000/" 2>/dev/null || echo "000")
    if [[ "$web_check" == "200" || "$web_check" == "303" ]]; then
        log_ok "VERIFY: Splunk Web accessible (HTTP ${web_check})"
        verify_passed=$((verify_passed + 1))
    else
        log_error "VERIFY: Splunk Web not accessible (HTTP ${web_check})"
    fi

    # Check indexes exist
    verify_total=$((verify_total + 1))
    local idx_check
    idx_check=$(curl -s -u "${SPLUNK_USER}:${SPLUNK_PASS}" \
        "http://${SPLUNK_SSH_HOST}:8089/services/data/indexes?output_mode=json&search=cribl_siem" 2>/dev/null | \
        python3 -c "import sys,json; d=json.load(sys.stdin); print(len(d.get('entry',[])))" 2>/dev/null || echo "0")
    if [[ "$idx_check" -ge 1 ]]; then
        log_ok "VERIFY: ${idx_check} cribl_siem index(es) found"
        verify_passed=$((verify_passed + 1))
    else
        log_warn "VERIFY: cribl_siem indexes not found via REST API (may need time)"
    fi

    # Summary
    echo ""
    echo "============================================================================="
    echo "  Splunk Configuration Summary (${SPLUNK_SSH_HOST})"
    echo "============================================================================="
    echo ""
    echo -e "  ${verify_passed}/${verify_total} verification checks passed"
    echo ""
    echo "  Configured:"
    echo "    - SIEM Indexes: cribl_siem, cribl_siem_windows, cribl_siem_linux"
    echo "    - HEC: Port ${SPLUNK_HEC_PORT:-8088}, Token: ${hec_token:0:8}..."
    echo "    - Sourcetypes: cribl:siem, cribl:siem:winsecurity, sysmon, auditd, linux_auth, sophos_fw, discovery"
    echo "    - CIM: Authentication, Endpoint, Network_Traffic, Change, Sophos"
    echo "    - Backup: ${BACKUP_DIR_REMOTE}"
    echo ""

    if [[ "$verify_passed" -eq "$verify_total" ]]; then
        echo -e "  ${GREEN}${BOLD}Splunk configuration successful!${NC}"
        echo ""
        echo "  Next steps:"
        echo "    1. Splunk Web: http://${SPLUNK_SSH_HOST}:8000"
        echo "    2. Search: index=cribl_siem | stats count by sourcetype"
        echo "    3. Deploy Cribl Routes: ./scripts/15-deploy-universal-classifier.sh"
        echo "    4. AI Panel: http://10.10.0.100:8080/docs/16-ai-status-panel.html"
        echo "    5. SIEM-Discovery: Find new SIEM sources in AI Panel"
    else
        echo -e "  ${YELLOW}${BOLD}Configuration completed with warnings. Review output above.${NC}"
    fi
    echo ""
}

main "$@"
